name: Download and Store Nifty50 Data

on:
  schedule:
    # 9:17 AM to 9:59 AM IST (3:46 AM to 3:59 AM UTC)
    - cron: "47-59/5 3 * * 1-5"
    # 10:00 AM to 2:59 PM IST (4:00 AM to 8:59 AM UTC)
    - cron: "0-59/5 4-8 * * 1-5"
    # 3:00 PM to 3:32 PM IST (9:00 AM to 10:31 AM UTC)
    - cron: "0-32/5 9-10 * * 1-5"
  workflow_dispatch:   # Manual trigger (optional)

jobs:
  download_and_store_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.30
          pip install pandas  # Install pandas and sqlite3

      # Step 2: Download Nifty50 data and save CSV files
      - name: Download Nifty50 Data
        run: |
          python3 scripts/download_nifty50_data.py  # Path to your download_nifty50_data.py script

      # Step 3: Store data from CSV files to SQLite database
      - name: Store CSV data to SQLite DB
        run: |
          python3 scripts/store_csv_to_db.py  # Path to your store_csv_to_db.py script

      # Step 4: Commit and push the updated database and CSV files
      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Stage the database and CSV files for commit
          git add temp_csv/*.csv nifty50_data_v1.db

          # Commit the changes
          git commit -m "Download Nifty50 data, store to DB, and update CSVs"

          # Push the changes back to the repository
          git push origin main  # Or the branch you want to push to
