name: Download and Store Nifty50 Data

on:
  schedule:
    - cron: '15 */1 * * 1-5'   # Runs every 15 minutes from Monday to Friday (9:15 AM to 3:30 PM IST)
  workflow_dispatch:   # Manual trigger (optional)

jobs:
  download_and_store_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.30

      # Step 2: Download Nifty50 data and save CSV files
      - name: Download Nifty50 Data
        run: |
          python3 scripts/download_nifty50_data.py  # Path to your download_nifty50_data.py script

      # Step 3: Commit and push the downloaded CSV files to GitHub
      - name: Commit and push CSV files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Stage CSV files for commit
          git add temp_csv/*.csv

          # Commit the CSV files
          git commit -m "Download Nifty50 data and save CSV files"

          # Push the changes back to the repository
          git push origin main  # Or the branch you want to push to
