name: Update README with Last 5 Rows

on:
  push:
    paths:
      - 'nifty50_data_v1.db'  # Path to your database file (or the folder where it's stored)
      - 'database/**'          # If the database is inside a folder, e.g. 'database/'
  
jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlite3 pandas  # Install sqlite3 and pandas (for reading CSV)

      # Step 3: Update README with last 5 rows from each table
      - name: Update README with last 5 rows
        run: |
          python3 scripts/update_readme.py  # Path to your update_readme.py script

      # Step 4: Commit and push the updated README
      - name: Commit and push updated README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Stage the updated README file for commit
          git add README.md

          # Commit the changes
          git commit -m "Update README with latest database entries"

          # Push the changes back to the repository
          git push origin main  # Or the branch you want to push to
