name: Update README with Last 5 Rows

on:
  schedule:
    # Schedule the workflow to run every hour from 9:15 AM to 3:30 PM IST, Monday to Friday
    - cron: '15 3-9 * * 1-5'  # Every hour from 9:15 AM to 3:30 PM IST (convert to UTC)
  workflow_dispatch:  # Allows for manual trigger from GitHub Actions UI

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the database and README
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies for SQLite and pandas
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tabulate

      # Update README with last 5 rows from each table in the database
      - name: Update README with last 5 rows
        run: |
          python3 scripts/update_readme.py  # Path to your Python script

      # Commit and push the updated README file
      - name: Commit and push updated README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md  # Stage README for commit
          git commit -m "Update README with latest database entries" || echo "No changes to commit"
          git push origin main  # Push changes to the main branch (or whichever branch you're working on)
